"""GymOS Interface Contracts — Protocol-based interfaces for all module boundaries.

Every module communicates with other modules exclusively through these interfaces.
Protocols enable structural typing: any object with matching method signatures
is a valid implementation, no explicit inheritance required.

Usage:
    from shared.interfaces import INutritionProvider, ITrainingProvider

    class CronometerProvider:
        \"\"\"Structural implementor of INutritionProvider — no inheritance needed.\"\"\"
        def get_today(self) -> DailyNutrition | None: ...
        def get_day(self, date: str) -> DailyNutrition | None: ...
        ...
"""

from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable

# ─── Forward type references (strings to avoid circular imports) ───


# ─── Training Provider ──────────────────────────────────────────

@runtime_checkable
class ITrainingProvider(Protocol):
    """Training domain data — sessions, exercises, volume, and PRs.

    Consumed by GymBrain rules and analysis engines.
    Implemented by DataProvider (GymBrain facade).
    """

    def get_exercise(self, exercise_id: str) -> dict[str, Any] | None: ...
    def get_exercise_by_name(self, name: str) -> dict[str, Any] | None: ...
    def get_all_exercises(self) -> list[dict[str, Any]]: ...
    def get_exercises_by_muscle(self, muscle_id: str) -> list[dict[str, Any]]: ...
    def get_exercises_by_category(self, category: str) -> list[dict[str, Any]]: ...

    def get_muscle(self, muscle_id: str) -> dict[str, Any] | None: ...
    def get_all_muscles(self) -> list[dict[str, Any]]: ...
    def get_muscles_by_group(self, group: str) -> list[dict[str, Any]]: ...

    def list_sessions(self, limit: int = 50, offset: int = 0) -> list[Any]: ...
    def get_session(self, session_id: int) -> Any | None: ...
    def get_last_session_for_exercise(self, exercise_name: str) -> Any | None: ...
    def get_recent_sessions(self, days: int = 14) -> list[Any]: ...

    def get_body_weight(self, date: Any = None) -> Any | None: ...
    def get_latest_body_weight(self) -> Any | None: ...
    def get_body_weight_history(self, days: int = 90) -> list[Any]: ...

    def get_recent_volume(self, days: int = 7) -> float: ...
    def get_volume_by_day(self, days: int = 90) -> list[dict[str, Any]]: ...
    def get_streak(self) -> int: ...
    def get_total_workouts(self) -> int: ...

    def get_program(self) -> dict[str, Any] | None: ...
    def get_program_exercise_ids(self) -> list[str]: ...
    def get_priority_muscles(self) -> list[str]: ...

    def calculate_effective_volume(self, exercise: Any, sets: list[Any]) -> list[Any]: ...
    def calculate_total_weekly_volume(self, weekly_exercises: list[tuple[Any, list[Any]]]) -> dict[str, float]: ...

    def detect_prs(self, session: Any) -> list[Any]: ...
    def analyse_session(self, session: Any) -> Any | None: ...
    def analyse_exercise(self, exercise_name: str, sets: list[Any], target_reps: str, acceptable_rir: int = 2) -> Any | None: ...
    def get_progression_recommendation(self, exercise_name: str) -> Any | None: ...


# ─── Nutrition Provider ────────────────────────────────────────

@runtime_checkable
class INutritionProvider(Protocol):
    """Nutrition domain data — daily intake, macros, targets, and hydration.

    Consumed by GymBrain nutrition rules and dashboard.
    Implemented by ProductionNutritionProvider and mock providers.
    """

    def get_today(self) -> Any | None: ...
    def get_day(self, date: str) -> Any | None: ...
    def get_recent_days(self, days: int = 7) -> list[Any]: ...
    def get_default_target(self) -> Any: ...
    def get_average_calories(self, days: int = 7) -> float: ...
    def get_average_protein(self, days: int = 7) -> float: ...
    def has_data(self) -> bool: ...
    def get_body_weight_history(self, days: int = 90) -> list[Any]: ...
    def get_latest_body_weight(self) -> Any | None: ...
    def get_summary(self) -> Any: ...


# ─── Recovery Provider ─────────────────────────────────────────

@runtime_checkable
class IRecoveryProvider(Protocol):
    """Recovery domain data — scores, fatigue, sleep, readiness.

    Consumed by GymBrain recovery rules and dashboard.
    """

    def get_recovery_score(self, date: str | None = None) -> float | None: ...
    def get_recovery_history(self, days: int = 14) -> list[dict[str, Any]]: ...
    def get_fatigue_score(self) -> float | None: ...
    def get_readiness_score(self) -> float | None: ...
    def get_sleep_hours(self, date: str | None = None) -> float | None: ...
    def get_hrv_score(self, date: str | None = None) -> float | None: ...
    def has_data(self) -> bool: ...


# ─── Goal Provider ─────────────────────────────────────────────

@runtime_checkable
class IGoalProvider(Protocol):
    """User goal data — targets, preferences, and progression context.

    Consumed by GymBrain goal analysis and recommendation ranking.
    """

    def get_current_goal(self) -> dict[str, Any] | None: ...
    def get_goal_weight(self) -> float | None: ...
    def get_target_calories(self) -> float | None: ...
    def get_target_protein(self) -> float | None: ...
    def get_preferred_workout_split(self) -> str | None: ...
    def get_available_days_per_week(self) -> int: ...
    def get_experience_level(self) -> str: ...


# ─── Knowledge Repository ──────────────────────────────────────

@runtime_checkable
class IKnowledgeRepository(Protocol):
    """Knowledge base — exercise definitions, muscle anatomy, aliases.

    The single entry point for all structured domain knowledge.
    No module reads knowledge/ files directly.
    """

    def get_exercise(self, exercise_id: str) -> dict[str, Any] | None: ...
    def get_exercise_by_name(self, name: str) -> dict[str, Any] | None: ...
    def get_all_exercises(self) -> dict[str, dict[str, Any]]: ...
    def get_exercises_by_category(self, category: str) -> list[dict[str, Any]]: ...
    def get_exercises_by_muscle(self, muscle_id: str) -> list[dict[str, Any]]: ...

    def get_muscle(self, muscle_id: str) -> dict[str, Any] | None: ...
    def get_all_muscles(self) -> dict[str, dict[str, Any]]: ...
    def get_muscles_by_group(self, group: str) -> list[dict[str, Any]]: ...

    def resolve_alias(self, name: str) -> list[str]: ...
    def get_alias_map(self) -> dict[str, str]: ...


# ─── Recommendation Engine ─────────────────────────────────────

@runtime_checkable
class IRecommendationEngine(Protocol):
    """GymBrain recommendation engine — evaluates rules and returns ranked recommendations."""

    def get_today_recommendations(self, max_recs: int = 10) -> list[Any]: ...
    def get_weekly_review(self) -> Any: ...
    def evaluate_rules(self, max_recommendations: int = 20) -> list[Any]: ...


# ─── Data Provider (GymBrain facade) ──────────────────────────

@runtime_checkable
class IDataProvider(ITrainingProvider, Protocol):
    """Composite data provider that aggregates all domain providers.

    This is the single facade consumed by GymBrain rules and analyzers.
    Combines training, nutrition, recovery, and goal data access.
    """

    @property
    def nutrition_provider(self) -> INutritionProvider | None: ...


__all__ = [
    "IDataProvider",
    "IGoalProvider",
    "IKnowledgeRepository",
    "INutritionProvider",
    "IRecommendationEngine",
    "IRecoveryProvider",
    "ITrainingProvider",
]
