"""GymOS Interface Contracts — Protocol-based interfaces for all module boundaries.

Every module communicates with other modules exclusively through these interfaces.
Protocols enable structural typing: any object with matching method signatures
is a valid implementation, no explicit inheritance required.

Usage::

    from shared.interfaces import INutritionProvider, ITrainingProvider

    class CronometerProvider:
        \"\"\"Structural implementor of INutritionProvider — no inheritance needed.\"\"\"
        def get_today(self) -> DailyNutrition | None: ...
        def get_day(self, date: str) -> DailyNutrition | None: ...
        ...
"""

from __future__ import annotations

from datetime import datetime

# ─── TYPE_CHECKING imports (never evaluated at runtime) ───────────
# These are needed only for the type-checker (mypy, pyright) to resolve
# concrete return/parameter types. Runtime uses the string annotations
# provided by ``from __future__ import annotations``.
from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

if TYPE_CHECKING:
    from modules.gymbrain.models.analysis import WeeklyReview
    from modules.gymbrain.models.recommendations import Recommendation
    from modules.nutrition.domain import DailyNutrition, MacroTarget, NutritionSummary
    from modules.prediction.domain import Prediction, PredictionResult
    from modules.recovery.domain import (
        DeloadPlan,
        ReadinessAssessment,
        RecoveryProfile,
        RecoveryRecommendation,
        RecoveryScore,
        RecoverySnapshot,
        RecoveryTrend,  # noqa: F401
        RecoveryTrendAnalysis,
        SleepLog,
        StressLog,
    )
    from modules.workout.domain import BodyWeight, SessionSet, WorkoutSession


# ─── Training Provider ──────────────────────────────────────────

@runtime_checkable
class ITrainingProvider(Protocol):
    """Training domain data — sessions, exercises, volume, and PRs.

    Consumed by GymBrain rules and analysis engines.
    Implemented by DataProvider (GymBrain facade).
    """

    def get_exercise(self, exercise_id: str) -> dict[str, Any] | None: ...
    def get_exercise_by_name(self, name: str) -> dict[str, Any] | None: ...
    def get_all_exercises(self) -> list[dict[str, Any]]: ...
    def get_exercises_by_muscle(self, muscle_id: str) -> list[dict[str, Any]]: ...
    def get_exercises_by_category(self, category: str) -> list[dict[str, Any]]: ...

    def get_muscle(self, muscle_id: str) -> dict[str, Any] | None: ...
    def get_all_muscles(self) -> list[dict[str, Any]]: ...
    def get_muscles_by_group(self, group: str) -> list[dict[str, Any]]: ...

    def list_sessions(self, limit: int = 50, offset: int = 0) -> list[WorkoutSession]: ...
    def get_session(self, session_id: int) -> WorkoutSession | None: ...
    def get_last_session_for_exercise(self, exercise_name: str) -> WorkoutSession | None: ...
    def get_recent_sessions(self, days: int = 14) -> list[WorkoutSession]: ...

    def get_body_weight(self, date: datetime | None = None) -> BodyWeight | None: ...
    def get_latest_body_weight(self) -> BodyWeight | None: ...
    def get_body_weight_history(self, days: int = 90) -> list[BodyWeight]: ...

    def get_recent_volume(self, days: int = 7) -> float: ...
    def get_volume_by_day(self, days: int = 90) -> list[dict[str, Any]]: ...
    def get_streak(self) -> int: ...
    def get_total_workouts(self) -> int: ...

    def get_program(self) -> dict[str, Any] | None: ...
    def get_program_exercise_ids(self) -> list[str]: ...
    def get_priority_muscles(self) -> list[str]: ...

    def calculate_effective_volume(self, exercise: dict[str, Any], sets: list[Any]) -> list[Any]: ...
    def calculate_total_weekly_volume(
        self, weekly_exercises: list[tuple[dict[str, Any], list[Any]]]
    ) -> dict[str, float]: ...

    def detect_prs(self, session: WorkoutSession) -> list[Any]: ...
    def analyse_session(self, session: WorkoutSession) -> Any | None: ...
    def analyse_exercise(
        self, exercise_name: str, sets: list[SessionSet], target_reps: str, acceptable_rir: int = 2
    ) -> Any | None: ...
    def get_progression_recommendation(self, exercise_name: str) -> Any | None: ...


# ─── Nutrition Provider ────────────────────────────────────────

@runtime_checkable
class INutritionProvider(Protocol):
    """Nutrition domain data — daily intake, macros, targets, and hydration.

    Consumed by GymBrain nutrition rules and dashboard.
    Implemented by ProductionNutritionProvider and mock providers.
    """

    def get_today(self) -> DailyNutrition | None: ...
    def get_day(self, date: str) -> DailyNutrition | None: ...
    def get_recent_days(self, days: int = 7) -> list[DailyNutrition]: ...
    def get_default_target(self) -> MacroTarget: ...
    def get_average_calories(self, days: int = 7) -> float: ...
    def get_average_protein(self, days: int = 7) -> float: ...
    def has_data(self) -> bool: ...
    def get_body_weight_history(self, days: int = 90) -> list[BodyWeight]: ...
    def get_latest_body_weight(self) -> BodyWeight | None: ...
    def get_summary(self) -> NutritionSummary: ...


# ─── Recovery Provider ─────────────────────────────────────────

@runtime_checkable
class IRecoveryProvider(Protocol):
    """Recovery domain data — scores, fatigue, sleep, readiness.

    Consumed by GymBrain recovery rules and dashboard.
    """

    def get_today_score(self) -> RecoveryScore | None: ...
    def get_score_by_date(self, date: str) -> RecoveryScore | None: ...
    def get_recent_scores(self, days: int = 7) -> list[RecoveryScore]: ...
    def get_latest_sleep(self) -> SleepLog | None: ...
    def get_sleep_by_date(self, date: str) -> SleepLog | None: ...
    def get_recent_sleep(self, days: int = 7) -> list[SleepLog]: ...
    def get_latest_stress(self) -> StressLog | None: ...
    def get_recent_stress(self, days: int = 7) -> list[StressLog]: ...
    def get_readiness(self) -> ReadinessAssessment | None: ...
    def get_recent_readiness(self, days: int = 7) -> list[ReadinessAssessment]: ...
    def get_active_deload(self) -> DeloadPlan | None: ...
    def get_recent_deloads(self, limit: int = 5) -> list[DeloadPlan]: ...
    def get_profile(self) -> RecoveryProfile: ...
    def get_recent_recommendations(self, days: int = 7) -> list[RecoveryRecommendation]: ...
    def has_data(self) -> bool: ...
    def get_average_score(self, days: int = 7) -> float: ...
    def get_snapshot(self) -> RecoverySnapshot: ...
    def get_trend(self, days: int = 14) -> RecoveryTrendAnalysis: ...


# ─── Goal Provider ─────────────────────────────────────────────

@runtime_checkable
class IGoalProvider(Protocol):
    """User goal data — targets, preferences, and progression context.

    Consumed by GymBrain goal analysis and recommendation ranking.
    """

    def get_current_goal(self) -> dict[str, Any] | None: ...
    def get_goal_weight(self) -> float | None: ...
    def get_target_calories(self) -> float | None: ...
    def get_target_protein(self) -> float | None: ...
    def get_preferred_workout_split(self) -> str | None: ...
    def get_available_days_per_week(self) -> int: ...
    def get_experience_level(self) -> str: ...


# ─── Knowledge Repository ──────────────────────────────────────

@runtime_checkable
class IKnowledgeRepository(Protocol):
    """Knowledge base — exercise definitions, muscle anatomy, aliases.

    The single entry point for all structured domain knowledge.
    No module reads knowledge/ files directly.
    """

    def get_exercise(self, exercise_id: str) -> dict[str, Any] | None: ...
    def get_exercise_by_name(self, name: str) -> dict[str, Any] | None: ...
    def get_all_exercises(self) -> dict[str, dict[str, Any]]: ...
    def get_exercises_by_category(self, category: str) -> list[dict[str, Any]]: ...
    def get_exercises_by_muscle(self, muscle_id: str) -> list[dict[str, Any]]: ...

    def get_muscle(self, muscle_id: str) -> dict[str, Any] | None: ...
    def get_all_muscles(self) -> dict[str, dict[str, Any]]: ...
    def get_muscles_by_group(self, group: str) -> list[dict[str, Any]]: ...

    def resolve_alias(self, name: str) -> list[str]: ...
    def get_alias_map(self) -> dict[str, str]: ...


# ─── Recommendation Engine ─────────────────────────────────────

@runtime_checkable
class IRecommendationEngine(Protocol):
    """GymBrain recommendation engine — evaluates rules and returns ranked recommendations."""

    def get_today_recommendations(self, max_recs: int = 10) -> list[Recommendation]: ...
    def get_weekly_review(self) -> WeeklyReview: ...
    def evaluate_rules(self, max_recommendations: int = 20) -> list[Recommendation]: ...


# ─── Prediction Provider ────────────────────────────────────────

@runtime_checkable
class IPredictionProvider(Protocol):
    """Prediction domain data — forecasts, PR probability, goal ETA, etc.

    Consumed by GymBrain predictive rules and dashboard.
    """

    def get_next_pr_probability(self, window: str = "7d") -> Prediction | None: ...
    def get_plateau_probability(self, window: str = "7d") -> Prediction | None: ...
    def get_recovery_forecast(self, window: str = "7d") -> Prediction | None: ...
    def get_bodyweight_forecast(self, window: str = "14d") -> Prediction | None: ...
    def get_goal_eta(self) -> Prediction | None: ...
    def get_mrv_risk(self) -> Prediction | None: ...
    def get_deload_probability(self) -> Prediction | None: ...
    def get_consistency_forecast(self, window: str = "14d") -> Prediction | None: ...
    def get_all_predictions(self) -> list[Prediction]: ...
    def get_prediction_result(self) -> PredictionResult: ...


# ─── Data Provider (GymBrain facade) ──────────────────────────

@runtime_checkable
class IDataProvider(ITrainingProvider, Protocol):
    """Composite data provider that aggregates all domain providers.

    This is the single facade consumed by GymBrain rules and analyzers.
    Combines training, nutrition, recovery, and goal data access.
    """

    @property
    def nutrition_provider(self) -> INutritionProvider | None: ...


# ─── Recovery Repository ────────────────────────────────────────

@runtime_checkable
class IRecoveryRepository(Protocol):
    """Abstraction for recovery data access in persistence layer."""
    pass


# ─── Progress Repository ────────────────────────────────────────

@runtime_checkable
class IProgressRepository(Protocol):
    """Abstraction for training progress data access in persistence layer."""

    def get_volume_by_day(self, days: int = 90) -> list[dict]: ...
    def get_body_weight_history(self, days: int = 90) -> list[Any]: ...
    def list_sessions(self, limit: int = 10) -> list[Any]: ...
    def get_latest_body_weight(self) -> float | None: ...
# ─── Workout Repository ─────────────────────────────────────────

@runtime_checkable
class IWorkoutRepository(Protocol):
    """Abstraction for workout and exercise history data access in persistence layer."""

    def get_program_days(self, program_name: str) -> list[Any]: ...
    def get_last_session_for_exercise(self, exercise_name: str) -> Any: ...
    def save_session(self, session: Any) -> Any: ...


__all__ = [
    "IDataProvider",
    "IGoalProvider",
    "IKnowledgeRepository",
    "INutritionProvider",
    "IPredictionProvider",
    "IRecommendationEngine",
    "IRecoveryProvider",
    "ITrainingProvider",
    "IRecoveryRepository",
    "IProgressRepository",
    "IWorkoutRepository",
]
