class NexusError(Exception): ...

class ConfigError(NexusError): ...

class DatabaseError(NexusError): ...

class PluginError(NexusError): ...

class ValidationError(NexusError): ...

class NotFoundError(NexusError): ...
